### ISSUE TITLE
Erro ao tentar configurar a Avaliação no novo módulo de Habilitação

### ISSUE THREAD

**Issue by Andreqlp** [hacklabr/mapasculturais#1213]
Ao tentar configurar a avaliação do projeto 
http://dev-mapa.cultura.ce.gov.br/oportunidades/edita/342/#tab=evaluations-config
aparece um erro inesperado com a seguinte descrição:

Um erro inesperado aconteceu
exception 'ErrorException' with message 'Trying to get property of non-object' in /srv/mapas/mapasculturais/src/protected/application/themes/BaseV1/layouts/parts/singles/opportunity-evaluations--config.php:6
Stack trace:
#0 /srv/mapas/mapasculturais/src/protected/application/themes/BaseV1/layouts/parts/singles/opportunity-evaluations--config.php(6): Slim\Slim::handleErrors(8, 'Trying to get p...', '/srv/mapas/mapa...', 6, Array)
#1 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Theme.php(360): include('/srv/mapas/mapa...')
#2 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Theme.php(387): MapasCulturais\Theme->partialRender('singles/opportu...', Array, true)
#3 /srv/mapas/mapasculturais/src/protected/application/themes/BaseV1/views/opportunity/single.php(75): MapasCulturais\Theme->part('singles/opportu...', Array)
#4 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Theme.php(360): include('/srv/mapas/mapa...')
#5 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Theme.php(267): MapasCulturais\Theme->partialRender('opportunity/edi...', Object(Slim\Helper\Set))
#6 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Theme.php(217): MapasCulturais\Theme->fullRender('opportunity/edi...')
#7 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/View.php(255): MapasCulturais\Theme->render('opportunity/edi...', NULL)
#8 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/View.php(243): Slim\View->fetch('opportunity/edi...', NULL)
#9 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/Slim.php(755): Slim\View->display('opportunity/edi...')
#10 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Controller.php(297): Slim\Slim->render('opportunity/edi...', Array)
#11 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Controllers/EntityController.php(312): MapasCulturais\Controller->render('edit', Array)
#12 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Controller.php(274): MapasCulturais\Controllers\EntityController->GET_edit()
#13 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/RoutesManager.php(176): MapasCulturais\Controller->callAction('GET', 'edit', Array)
#14 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/RoutesManager.php(106): MapasCulturais\RoutesManager->callAction(Object(MapasCulturais\Controllers\Opportunity), 'edit', Array, false)
#15 [internal function]: MapasCulturais\RoutesManager->MapasCulturais\{closure}(Array)
#16 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#17 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()
#18 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#19 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#20 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#21 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/Slim.php(1300): Slim\Middleware\PrettyExceptions->call()
#22 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/App.php(518): Slim\Slim->run()
#23 /srv/mapas/mapasculturais/src/index.php(4): MapasCulturais\App->run()
#24 {main}

**Comment by Andreqlp** [comment]
tá funcionando que é uma beleza
